version: '3.8'

services:
  backend:
    build: .
    container_name: voiceai-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://bingumallagreeshmitha_db_user:Blg270206@mongo-cluster.mm65oeb.mongodb.net/
    restart: unless-stopped